title:            Consequential Technologies, LLC
email:            drwahl@consequential.tech
description:      ""
baseurl:          ""
url:              "https://consequential.tech"
github_username:  consequentialtech
google_analytics: UA-163901255-1

markdown:         kramdown
theme:            minima
plugins:
  - jekyll-feed
